### ISSUE TITLE
Test failures - NullReferenceException - getResourceAsStream

### ISSUE THREAD

**Issue by AlexAddisonLN** [mitre/quaerite#52]
In TestGenerateESExperiments and TestGenerateSolrExperiments resources are used. Running these tests on my machine, the resources couldn't be reached using `TestGenerateESExperiments.class.getClass().getResourceAsStream("/test-documents/experiment_features_es_1.json")` and so I had to change them to this format: `TestGenerateESExperiments.class.getResourceAsStream("/test-documents/experiment_features_es_1.json")`

For reference, my machine is running Windows 10, and `java -version` gives 
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by tballison** [comment]
Thank you for opening this issue.  Please let me know if aed438b actually fixed it for you!

**Comment by AlexAddisonLN** [comment]
I believe so, yes
